blog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='blog-home'),
    path('group/<int:pk>/', views.group_detail, name='group_detail'),
    path('about/', views.about, name='blog-about'),
    path('post_new/', views.post_new, name='post_new'),
    path('detail/<int:pk>/', views.post_detail, name='post_detail'),
    path('delete/<int:pk>/', views.post_delete, name='post_delete'),
    path('edit/<int:pk>/', views.post_edit, name='post_edit'),
]

users/urls.py
from django.urls import path
from . import views

app_name="users"

urlpatterns = [
    path('group_find/', views.group_find , name='group_find'),

]

yong/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from users import views as user_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('register/', user_views.register, name='register'),
    path('profile/', user_views.profile, name='profile'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('', include('blog.urls')),
    path('users/', include('users.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from imagekit.models import ProcessedImageField
from imagekit.processors import Thumbnail


class Post(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    photo = ProcessedImageField(blank=True,
                                processors=[Thumbnail(300, 300)],
                                format='JPEG',
                                options={'quality': 60})
    date_posted = models.DateTimeField(default=timezone.now)
    author = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

class Comment(models.Model):
    post = models.ForeignKey(Post, related_name='comments', on_delete=models.CASCADE)
    author = models.CharField(max_length=50)
    message = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def approve(self):
        self.approved_comment = True
        self.save()

    def __str__(self):
        return self.text

blog/forms.py
from django import forms
from .models import Comment, Post
from users.models import Group


class GroupForm(forms.ModelForm):
    class Meta:
        model = Group
        fields = ('group_name', 'group_info', 'group_img', 'group_open_status')


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('message',)


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('title', 'content', 'photo',)

blog/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone

from .models import Post
from users.models import Profile, Group, GroupMember
from .forms import GroupForm, CommentForm, PostForm


@login_required
def home(request):
    profile = Profile.objects.get(user=request.user)
    ctx = {}
    user_groups = profile.group.all()

    if len(user_groups) > 0:
        ctx['user_groups'] = user_groups
        ctx['hasGroup'] = True

    else:
        ctx['hasGroup'] = False

    return render(request, "blog/home.html", ctx)


# from .models import Group, Post
#
#
# def home(request):
#     context = {
#         'posts': Post.objects.all(),
#         'groups': Group.objects.all()
#     }
#     return render(request, 'blog/home.html', context)
#
#
def group_detail(request, pk):
    group = get_object_or_404(Group, pk=pk)
    posts = Post.objects.all()
    hi = {
        'group': group,
        'posts': posts,
    }
    return render(request, 'blog/group_detail.html', hi)


# @login_required
def profile_revise(request):
    if request.method == 'POST':
        form = UserEditForm(request.POST, request.FILES, instance=request.user)
        if form.is_valid():
            us = form.save()
            return redirect("accounts:profile")
    else:
        profileform = UserEditForm(instance=request.user)
        forms = {'profileform': profileform}
        return render(request, 'accounts/profile_revise.html', forms)


def about(request):
    # return render(request, 'blog/about.html', {'title': 'About'})
    if request.method == "POST":
        form = GroupForm(request.POST)
        if form.is_valid():
            group = form.save(commit=False)
            group.group_creator = request.user
            group.created_date = timezone.now()
            group.save()

            GroupMember.objects.create(person=request.user.profile, group=group, status='a')

            return redirect('blog-home')
    else:
        form = GroupForm()
    return render(request, 'blog/about.html', {'form': form})


def login(request):
    return render(request, 'users/login.html')


# sulmo
def post_detail(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.post = post
            comment.author = request.user
            comment.save()
            return redirect('post_detail', pk=post.pk)
    else:
        form = CommentForm()
    return render(request, 'blog/post_detail.html', {'post': post, 'form': form})


def post_new(request):
    if request.method == 'POST':
        post = Post()
        post.title = request.POST['title']
        post.author = request.user
        post.content = request.POST['content']
        post.photo = request.FILES['photo']
        post.save()
        return redirect('blog-home')
    else:
        form = PostForm()
    return render(request, 'blog/post_new.html', {'form': form})


def post_delete(request, pk):
    post = get_object_or_404(Post, pk=pk)
    post.delete()
    return redirect('blog-home')


def post_edit(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES, instance=post)
        if form.is_valid():
            post = form.save()
            return redirect('blog-home')
    else:
        form = PostForm(instance=post)
    return render(request, 'blog/post_new.html', {
        'form': form,
    })
#
# def invite(request):
#     return render(request, 'blog/notification/friends_invite_sent/notice.html')

blog/templates/blog/about.html
{% extends "blog/base.html" %}
{% load i18n %}

{% block content %}
    <div id="title"><h1>New Group</h1></div>
    <form method="POST" class="">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-default">Save</button>
        {% blocktrans with invitation.to_user as invitation_user %}<a href="{{ user_url }}">{{ invitation_user }}</a>
            has accepted your friend request.{% endblocktrans %}
    </form>

{% endblock content %}

blog/templates/blog/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>

    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="{% static 'blog/main.css' %}">


    {% if title %}
        <title>Piro Board - {{ title }}</title>
    {% else %}
        <title>Piro Board</title>
    {% endif %}
</head>
<body>

<header class="site-header">
    <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
        <div class="container">
            <a class="navbar-brand mr-4" href="{% url 'blog-home' %}">Piro Board</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle"
                    aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarToggle">
                <div class="navbar-nav mr-auto">
                    <a class="nav-item nav-link" href="{% url 'blog-home' %}">Home</a>
                </div>
            <div class="navbar-nav mr-auto">
                    <a class="nav-item nav-link" href="{% url 'users:group_find' %}">find group</a>
                </div>
                <div class="dropdown-menu" aria-labelledby="dropdown04">
                    <a class="dropdown-item" href="#">Action</a>
                    <a class="dropdown-item" href="#">Another action</a>
                    <a class="dropdown-item" href="#">Something else here</a>
                </div>

                <!-- Navbar Right Side -->
                <div class="navbar-nav">
                    {% if user.is_authenticated %}

                        <form class="form-inline my-2 my-md-0">
                            <input class="form-control" type="text" placeholder="유저 및 그룹 검색">
                        </form>

                        <a class="nav-item nav-link" href="{% url 'profile' %}">프로필</a>
                        <a class="nav-item nav-link" href="{% url 'blog-about' %}">그룹 생성하기</a>
                        <a class="nav-item nav-link" href="{% url 'logout' %}">로그아웃</a>

                    {% else %}
                        <a class="nav-item nav-link" href="{% url 'login' %}">로그인</a>
                        <a class="nav-item nav-link" href="{% url 'register' %}">회원가입</a>
                    {% endif %}
                </div>

            </div>
        </div>
    </nav>
</header>
<main role="main" class="container">
    <div class="row">
        <div class="col-md-12">
            {% if messages %}
                {% for message in messages %}
                    <div class="alert alert-{{ message.tags }}">
                        {{ message }}
                    </div>
                {% endfor %}
            {% endif %}
            {% block content %}{% endblock %}
        </div>
        {#        <div class="col-md-4">#}
        {#                      <div class="content-section">#}
        {#                        <h3>Our Sidebar</h3>#}
        {#                        <p class='text-muted'>You can put any information here you'd like.#}
        {#                          <ul class="list-group">#}
        {#                            <li class="list-group-item list-group-item-light">Latest Posts</li>#}
        {#                            <li class="list-group-item list-group-item-light">Announcements</li>#}
        {#                            <li class="list-group-item list-group-item-light">Calendars</li>#}
        {#                            <li class="list-group-item list-group-item-light">etc</li>#}
        {#                          </ul>#}
        {#                        </p>#}
        {#                      </div>#}
        {#        </div>#}
    </div>
</main>

<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>


<link rel="stylesheet" href="https://cdn.jsdelivr.net/bxslider/4.2.12/jquery.bxslider.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
<script src="https://cdn.jsdelivr.net/bxslider/4.2.12/jquery.bxslider.min.js"></script>

<script>
    $(document).ready(function () {
        $('.bxslider').bxSlider();
    });

    $('.bxslider').bxSlider({mode: 'fade', captions: true});


</script>

<script>
    $(window).load(function () {
        $(".loading").fadeOut();
    });
</script>
</body>
</html>

blog/templates/blog/group_detail.html
{% extends "blog/base.html" %}

{% block content %}


    {#    sulmo 임시 확이용#}
    <div class="rows">
        {% if user.is_authenticated %}
            <a href="{% url 'post_new' %}">글쓰기</a>
        {% endif %}
        <br>
        {% for post in posts %}
            제목 : {{ post.title }}<br>
            내용 : {{ post.content }}<br>
            <a href="{% url 'post_detail' post.pk %}">드루와</a>
            <hr>
        {% endfor %}
    </div>
    <hr>
    {#   end sulmo 임시 확인용#}
<div class="container" style="height:700px;">
{#    <div class="loading"></div>#}

    <h1>
        <div id="title"><h1>{{ group.group_name }}</h1></div>
    </h1>

    <ul class="bxslider">
        <li><img
                src="https://previews.123rf.com/images/mexrix/mexrix1206/mexrix120600069/14260342-brown-cork-board-for-background.jpg"
                title="인물">
        </li>
        <li><img
                src="https://previews.123rf.com/images/mexrix/mexrix1206/mexrix120600069/14260342-brown-cork-board-for-background.jpg"
                title="음식">
        </li>
        <li><img
                src="https://previews.123rf.com/images/mexrix/mexrix1206/mexrix120600069/14260342-brown-cork-board-for-background.jpg"
                title="취미">
        </li>
        <li><img
                src="https://previews.123rf.com/images/mexrix/mexrix1206/mexrix120600069/14260342-brown-cork-board-for-background.jpg"
                title="etc">
        </li>
    </ul>
</div>



{% endblock %}

blog/templates/blog/home.html
{% extends "blog/base.html" %}
{% block content %}
    <div id="title"><h1>{{ user }}의 그룹</h1></div>
    <hr>

    <hr>
    <div>
        {% if hasGroup %}
            <h2>당신은 현재 {{ user_groups.count }}개의 그룹에 속해 있습니다.</h2>
            <div>
                {% for group in user_groups %}
                    <article class="media content-section">
                        <div class="media-body">
                            <div class="article-metadata">
                                <a class="mr-2" href="{% url 'profile' %}">{{ group.group_name }}</a>
                                {#                                <small class="text-muted">{{ group.created_date|date:"F d, Y" }}</small>#}
                            </div>

                            {#                            <h2><a class="article-title"#}
                            {#                                   href="{% url 'group_detail' pk=group.pk %}">{{ group.group_name }}</a></h2>#}
                            <p class="article-content">{{ group.group_info }}</p>
                                <a href="{% url 'group_detail' group.pk %}">그룹 자세히</a> {#sulmo#}
                            <button class="button2 btn login_btn">초대할 대상 찾기</button>
                        </div>
                    </article>
                {% endfor %}
            </div>
        {% else %}
            <h2>없음</h2>
        {% endif %}
    </div>


{% endblock content %}

blog/templates/blog/makegroup.html
{% extends 'blog/base.html' %}

{% block content %}
    <h1>New post</h1>
    <form method="POST" class="group-form">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-default">Save</button>
    </form>
{% endblock %}

blog/templates/blog/post_detail.html
{% extends "blog/base.html" %}
{% block content %}
    <h2>detail page</h2><hr>
    제목 : {{post.title}} <br>
    내용 : {{post.content}}<br>
{% if post.photo %}
<img src="{{post.photo.url}}" alt=""><hr>

{% endif %}

    작성자 : {{post.author}}
<hr>
<a href="{% url 'post_delete' post.pk %}">삭제</a>
<a href="{% url 'post_edit' post.pk %}">수정</a>
<hr>
<h3>댓글</h3>

<br>
    <h1>New comment</h1>
{% if user.is_authenticated %}
    <form method="POST" class="post-form">
        {% csrf_token %}
        작성자 : {{ request.user }}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-default">Send</button>
    </form>
    <br>
{% endif %}

{% for comment in post.comments.all %}
    <div class="comment">
        <div class="date">
            {{ comment.created_date }}
        </div>
        <strong>작성자 : {{ comment.author }}</strong>
        <p> {{ comment.message|linebreaks }}</p>
        <hr>
    </div>
{% empty %}
    <p>No comments here yet :(</p>
{% endfor %}

{% endblock content %}

blog/templates/blog/post_new.html
{% extends "blog/base.html" %}
{% block content %}
<h3>글쓰기</h3>

<form action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_table }}

<!--    <input type="text" name="title">-->
<!--    <textarea name="content" id="" cols="30" rows="10"></textarea>-->
    <input type="submit" value="팍">
</form>

{% endblock content %}